### PR TITLE
Topic/fix sobel shader issue

### PR DESCRIPTION
**Pull request by gergondet**
Dear all,

This PR proposes two things:
- a new executable that test all the ImageProcessing algorithms on the infamous lenna.png file
- fix an unitialized issue in sobel fragment shader (caused big problem on recent nvidia drivers)

Best,

### CODE REVIEW

**Comment by bmagyar** [comment]
I also think that having a input/output fixed sample set would be nice. We could even have multiple test sources if necessary. What do you think about changing this node approach into a rostest or gtest? 

That way, plus with the fixed samples one could quickly test blort on their system by runnig catkin_make run_tests

**Comment by gergondet** [comment]
Hi,

I'm not sure this would work well across different machines because of different versions of OpenCV and other dependencies involved in this test. That would not be difficult to try though so I will give it a go within the next week(s). At the very least, we could provide a set of result images for visual comparison. For example, in the case of the sobel shader, the outcome with improperly initialized variables was totally messed up.

Best,

**Comment by jordi-pages** [comment]
mm, I think you're right. I agree that different versions/compilations of OpenCV can provide slightly different results. Perhaps some synthetic simple binary images could provide constat results accross platforms. Otherwise, +1 for result image for visual comparison.

**Comment by bmagyar** [comment]
Could you please add 2 more images to the PR, one a good result and a bad one you've encountered? 
Once they are there, I'll merge the PR and keep it as visual test for now :+1:

**Comment by gergondet** [comment]
Hi everybody and happy new year!

I've updated the PR with reference images for the output of the different ImageProcessor methods. The test executable will also perform a comparison between the output and the reference I've provided. To overcome slight difference between different platform/environment, it won't report any problem if the difference is small.

"Unfortunately" since the start of the PR I've updated my nvidia drivers and I cannot reproduce the noisy output that I got before.

**Comment by bmagyar** [comment]
All seems well. Tonight I will give it a shot and if it works (fails or succeeds depending on my nvidia driver :)) I'll merge it right away :+1:

**Comment by bmagyar** [comment]
Tested, works! Thanks for the contribution again!

**Pull request merged**
