### PR TITLE
Migrated to hydro and catkinized

### PR DESCRIPTION
**Pull request by bmagyar**

### CODE REVIEW

**Comment by bmagyar** [comment]
The install rules are missing, but I need this here to put in rosinstall.

**Comment by po1** [comment]
It's nice to open pull requests, but if you merge them yourself within 1 minute of opening them, then what's the point?

**Comment by bmagyar** [comment]
- To make notes
- To tag incoming stuff
- To attract trolls

**Comment by po1** [comment]
In the end, you just love that big green button, don't you?

:trollface:

**Pull request merged**
