### PR TITLE
Create blort_ros_msgs + Allow rosbuild/catkin switch

### PR DESCRIPTION
**Pull request by gergondet**
Hello,

This PR addresses two things:
- Create a separate package to hold the messages and services related to blort_ros, this is particularly helpful to make use of BLORT without having to compile it
- Allow to switch between rosbuild and catkin: it defaults to catkin

I have not been able to test the compilation using catkin so I'm interested to know if it's working.

Best

### CODE REVIEW

**Comment by bmagyar** [comment]
I appreciate the work you do but I'm afraid I cannot merge this as is. The package has to stick to a standard method of compiling, we cannot have the bash script.

What blocks you from using catkin? Are you using fuerte?
I had an example cmake file somewhere which worked with both catkin and rosbuild, but if nothing else the dynamic reconfigure would still break...

**Comment by po1** [comment]
It might be easier to use a separate branch. It is a bit more work to merge all the changes back and forth, but in the end it's easier for the end-user, and helps keeping things clean.

Catkin can be very easily installed without any ROS package. I highly recommend you give it a try. As much as I appreciate the efforts to maintain backwards compatibility, rosbuild is pretty broken and its use is deprecated.

**Comment by gergondet** [comment]
I get your points and they seem fair to me. The machine where I do most of my work is still running fuerte but I guess this is becoming a thing of the past :-)

I'll redo a PR that fully embrace catkin :+1:

**Comment by bmagyar** [comment]
Arigato :+1:

**Pull request closed without merging**
