### PR TITLE
Config refactor

### PR DESCRIPTION
**Pull request by v-lopez**
- Add missing config files
- Add install rules so that tutorials can be executed from the installed package
- Move config files from bin to config

### CODE REVIEW

**Comment by po1** [comment]
This is probably not what you are doing here, but I'd like to highlight that config files in a such a package should be example files to be copied to a package actually targeting an application platform, such as a robot. It is a good place to document default values for parameters.

**Comment by bmagyar** [comment]
Those configs are rather fixed, not robot related, plus they are supplied to make sure that the tutorials/top level tests can be completed.

**Comment by bmagyar** [comment]
Thanks for making some order with those config files!

**Comment by po1** [comment]
@bmagyar they should have nothing to do with the top-level tutorials/tests. If these need a specific config, they should have their own. If you use configuration values from the same package, you should provide an easy way to override it, e.g. a `config_file` roslaunch argument, that would default to the one in this package.

**Pull request merged**
